"""feat(models): add relationship to User and Expense and is_active to User model

Revision ID: 1fad0ce7e859
Revises: 8b55c4f25242
Create Date: 2026-03-20 19:18:47.923324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fad0ce7e859'
down_revision: Union[str, Sequence[str], None] = '8b55c4f25242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
