"""fix typo in User

Revision ID: 6f11d5f6ebb4
Revises: 1fad0ce7e859
Create Date: 2026-03-20 20:29:00.897892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f11d5f6ebb4'
down_revision: Union[str, Sequence[str], None] = '1fad0ce7e859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
